baseURL = "https://secil.univ-tlse3.fr/ontheroadagain"
languageCode = "fr"
title = "On The Road Again..."
theme = "story"
paginate = 5
publishDir = "public"

[[menu.main]]
  name = "Blogs"
  title = "Blogs"
  url = "/blogs/"
  weight = 3

[[menu.main]]
  name = "Doc"
  title = "Doc"
  url = "/docs/"
  weight = 2

[[menu.main]]
  name = "News"
  title = "News"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Authors"
  title = "Authors"
  url = "/authors/"
  weight = 4

